sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bJepuIckM5CYc08WGExDrU+tWSCN2sfdJm22K7qQIDWnl8Mo4s4c7fbWDbF0bZtjhePxkvQXClj68E4DSfaoRXw6Lwy/wGSDgqmEKZwt74E8p8W/5gpX6k07cQE0WiacnXz3+xDU+MttFKY0ZCksffC1B0iBW5uEn8gBdoLhEBoo3zuD+zOgExUX22bIgEGCY9OvmhKIhdzMe7HuM2xGTwdkaQUD5VIhDhkjA6J3Bl5n5NPNpRWsiDiiwDWyBTObMR4I5O/zFrnBkpItGhH2PEnxrcMNwPPLIUdhJ776XtnUo6vzs0Vl7RtPhZHGvoGR/RdMJzhEP58Pq/DKv74VqcSMOTvTBvs6axX/bHYZtk87T7Px3R76SoIB/JoA8Rlr2Q8UonpBpC9Od/EZLKxLkKdT6dqUfFXFWY/tGibLy1Q+mZxshJnh8/l/7yEead739DFZ+zZ/gJ+blyuq4AyEFWwrZ1IIG9+a6KsKKp1g6gQ8oT5Gdl1D00cmvh2u2Hf3+Y2W2wTaZ5WuXkVn4yVgJgrlUAlqZHB/djUURHTZGwJWZxhKroah5r4zBLhrZAg8WS5Cpms3ssf/iwahZkKAvX8aSPXM3kfU2LOTYyQqje3hSHQIa/GALxodcWFsBbf+9b+l/uGYq1vC3vUoZTefb3x831zYKMurOi7C7mhEzi4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Project-Gutenberg-Encyclopedia--13-Volume-1-of-28_200
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy